#!/usr/bin/env sh
# Give a battery name (e.g. BAT0) as an argument.

case $BLOCK_BUTTON in
    3) pgrep -x dunst >/dev/null && notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Text color reflects charge left" ;;
esac

capacity=$(cat /sys/class/power_supply/BAT0/capacity) || exit
status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$capacity" -ge 95 ]; then
	color="#00ff00"
	symbol=""
elif [ "$capacity" -ge 50 ]; then
	color="#ffffff"
	symbol=""
elif [ "$capacity" -ge 25 ]; then
	color="#ffff00"
	symbol=""
elif [ "capacity" -ge 10 ]; then
	color="#ff0000"
	symbol=""
else
	color=
	symbol=""
fi

[ -z $warn ] && warn=" "

[ "$status" = "Charging" ] && color="#ffffff"

printf "%s%s%s\n" "$(echo "$status" | sed -e "s/,//;s/Discharging/"$symbol"/;s/Charging/ /;s/Unknown/ /;s/Full//;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/% /')";
