#!/bin/sh

bg_color=#2f343f
text_color=#f3f4f5
htext_color=#9575cd

rofi -show run -lines 5 -eh 2 -width 100 -padding 700  -opacity "90" -bw 0 -color-window "$bg_color, $bg_color, $bg_color" -color-normal "$bg_color, $text_color, $bg_color, $bg_color, $htext_color" -font "System San Francisco Display 16"

